config/routes.rb
Rails.application.routes.draw do
  scope module: 'authors' do
    get 'stats' => 'stats#index'
    resources :posts do
      resources :elements
    end
  end
  devise_for :authors
  get 'home/index'
  root to: "readers/home#index"
  get '/blog/:id' => 'readers/posts#show', as: :blog_post


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph' ,'image', 'video-embed']}

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/page_view.rb
class PageView < Impression
  scope :for_type, -> (type) do
    where(Impressionable_type: type)
  end

  scope :for_date_range, -> (start_date, end_date) do
    where(created_at: start_date.beginning_of_day..end_date.end_of_day)
  end

  def self.count_by_date(start_date, end_date)
    results = for_date_range(start_date, end_date).group('date(created_at)').count

    with_zeros(start_date, end_date, results)
  end

  def self.uniq_count_by_date(start_date, end_date)
    results = for_date_range(start_date, end_date).select(:ip_address).distinct.group('date(created_at)').count
    with_zeros(start_date, end_date, results)
  end

  def self.with_zeros(start_date, end_date, results_hash)
    date_range = (start_date.to_date..end_date.to_date).to_a.map do |date|
      date
    end
    hash_with_zeros = {}
    date_range.each do |date|
      hash_with_zeros[date] = results_hash[date] || 0
    end
    hash_with_zeros
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  is_impressionable

  belongs_to :author
  has_many :elements

  has_one_attached :header_image

  validates_presence_of :title, :description
  validates_length_of :description, within: 50..250

  scope :published, -> do
    where(published: true)
  end

  scope :most_recently_published, -> do
    order(published_at: :desc)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_action_cable_identifier

  private

  def set_action_cable_identifier
    cookies.encrypted[:author_id] = current_author&.id
  end
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: [:update, :destroy]

    # POST /elements
    def create
      @element = @post.elements.new(element_params)

      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join(".") << "."
      end
      redirect_to edit_post_path(@post), notice: notice
    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      # redirect_to edit_post_path(@element.post)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post)
    end

    private

      def set_post
        @post = current_author.posts.find(params[:post_id])
      end
      # Use callbacks to share common setup or constraints between actions.
      def set_element
        @element = @post.elements.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def element_params
        params.require(:element).permit(:element_type, :content, :image)
      end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
      # @paragraph = @post.elements.build(element_type: 'paragraph')
      # @image = @post.elements.build(element_type: 'image')
    end

    # POST /posts
    def create
      @post = current_author.posts.new(post_params)

      if @post.save
        redirect_to edit_post_path(@post), notice: 'Post was successfully created.'
      else
        broadcast_errors @post, post_params
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post), notice: 'Post was successfully updated.'
      else
        broadcast_errors @post, post_params
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image)
      end
  end
end

app/controllers/authors/stats_controller.rb
module Authors
  class StatsController < AuthorsController
    def index
      @count_by_date = PageView.count_by_date(7.days.ago, Date.today).to_json
      @unique_count_by_date = PageView.uniq_count_by_date(7.days.ago, Date.today).to_json
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/readers/home_controller.rb
module Readers
  class HomeController < ReadersController
    def index
      @posts = Post.published.most_recently_published
    end
  end
end

app/controllers/readers/posts_controller.rb
module Readers
  class PostsController < ReadersController
    def show
      @post = Post.published.friendly.find(params[:id])
      impressionist(@post)
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  layout 'readers'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/elements/update.js.erb
var element = document.getElementById('element-<%= @element.id %>-form')

element.classList.add('d-none')
element.previousElementSibling.classList.remove('d-none')


var html = "<div class='trix-content'><%= @element.content.body.html_safe %></div>"
element.previousElementSibling.classList.innerHTML = html

app/views/authors/posts/_form.html.slim
= form_with(model: post) do |form|
  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'
    = form.error_for :title, class: 'text-danger'
  .form-group
    = form.label :description
    = form.text_area :description, class: 'form-control'
    = form.error_for :description, class: 'text-danger'

  .form-group
    = form.label :header_image
    = form.file_field :header_image
    .mt-1
      - if post.header_image.present?
        small
          | current image:
          = image_tag(post.header_image, width: '100%')
  .actions
    = form.submit class: 'btn btn-primary btn-block'

app/views/authors/posts/edit.html.slim
/ div[data-controller="hello"]
/   input[data-target="hello.name" type="text"]
/   button[data-action="click->hello#greet"]
/     |  Greet 
/   span[data-target="hello.output"]
.row
  .col-md-4
    = link_to 'Back', posts_path, class: 'btn btn-dark mb-3 text-white'
    .card
      .card-header
        h6.card-title.mb-0
          | Editing Post
      .card-body
        = render 'form', post: @post
      .card-footer
        - if @post.published?
          a.btn.btn-secondary.btn-block href="#" data-reflex='click->PublisherReflex#unpublish' data-post-id='#{ @post.id}'
            | Unpublished
        - else
          a.btn.btn-dark.btn-block href="#" data-reflex='click->PublisherReflex#publish' data-post-id='#{@post.id}'
            | published
  .col-md-8
    .mb-3
      = form_with(model: [@post, @element], html: { class: 'float-left mr-1'}) do |form|
        = form.hidden_field :element_type, value: 'paragraph'
        = button_tag(type: 'submit', class: 'btn btn-secondary') do
          i.fas.fa-paragraph
      = form_with(model: [@post, @element]) do |form|
        = form.hidden_field :element_type, value: 'image'
        = button_tag(type: 'submit', class: 'btn btn-secondary') do
          i.fas.fa-images
    .card.mb-5
      .card-header.text-right
        - if @post.published?
          b.mr-2
            | Published
          |#{time_ago_in_words(@post.published_at)}ago
        - else
          | Unpublished

      .card-body.pt-5 data-controller="elements"
        - if @post.elements.none? {|element| element.persisted?}
          .p-4.text-center
            h2.text-secondary
              i.fas.fa-lightbulb
            p
              | 上のアイコンをクリックしてください
        -else
          ul id='elements'
            - @post.elements.order(position: :asc).each do |element|
              - if element.persisted?
                li.element-item[data-id="#{element.id}"]
                  - if element.paragraph?
                    .mb-3.p-3.paragraph
                      .paragraph-content
                        - if element.content.present?
                          = raw element.content
                        - else
                          | Click
                      .paragraph-form.d-none id='element-#{element.id}-form'
                        = form_with(model: [@post, element]) do |form|
                          = form.rich_text_area :content
                          .mt-3.d-flex.justify-content-between
                            div
                              = form.submit "保存する", class: 'btn btn-primary mr-2'
                              a.cancel.btn.btn-secondary[href="#"]
                                | キャンセル
                            = link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?'}
                  - elsif element.image?
                    .image.mb-4.p-3
                      - if element.image.present?
                        = link_to post_element_path(@post, element), method: :delete, class: 'delete-btn btn btn-dark mt-2 float-right', data: { confirm: 'Are you sure?'} do
                          i.fas.fa-times
                        = image_tag(element.image)
                      - else
                        = form_with(model: [@post, element]) do |form|
                          = form.file_field :image
                          = form.submit "保存する", class: 'btn btn-primary mt-3 mr-2'
                          a.mt-3.cancel.btn.btn-secondary[href="#"]
                            | キャンセル

app/views/authors/posts/index.html.slim
h4.d-flex.justify-content-between.mb-4
  | Posts
  = link_to 'New Post', new_post_path, class: 'btn btn-primary text-white'

- @posts.each do |post|
  = link_to edit_post_path(post), class: 'text-decoration-none' do
    .card.mb-3.post-card
      .card-body
        .row
          .col-md-2
            - if post.header_image.present?
              = image_tag post.header_image, class: 'header-img'

          .col-md-10
            - if post.published?
              .span.badge.badge-primary
                | Published
            - else
              span.badge.badge-secondary
                | Unpublished
            h5.card-title.mb-1.text-dark
              = post.title
            p.text-secondary.mb-0
              = post.description

app/views/authors/posts/new.html.slim
.row
  .col-md-4
    = link_to 'Back', posts_path, class:'btn btn-dark mb-3'
    .card
      .card-header
        h6.card-title.mb-0
          | New Post

      .card-body
        = render 'form', post: @post

app/views/authors/posts/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @post.title
p
  strong
    | Description:
  = @post.description
p
  strong
    | Published:
  = @post.published
p
  strong
    | Published at:
  = @post.published_at
p
  strong
    | Author:
  = @post.author_id
= link_to 'Edit', edit_post_path(@post)
|  | 
= link_to 'Back', posts_path

app/views/authors/stats/index.html.slim
h4.mb-4
  | 統計
.row
  .col-md-6
    .card
      .card-header
        | 7 Day Views
      .card-body
        canvas#page-views[width="400" height="400" data-labels='#{@count_by_date}']
  .col-md-6
    .card
      .card-header
        | 7 Day Unique Views
      .card-body
        canvas#unique-page-views[width="400" height="400" data-labels='#{@unique_count_by_date}']

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SampleApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/layouts/authors.html.slim
doctype html
html
  head
    title
      | SampleApp
    = csrf_meta_tags
    = csp_meta_tag
    link[rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"]

    link[href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"]
    
    script[src="https://code.jquery.com/jquery-3.4.1.slim.min.js"]
    script[src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"]
    script[src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"]
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-light.authors
    .container
      p.notice
        = notice
      p.alert
        = alert
      = yield

app/views/layouts/readers.html.slim
doctype html
html
  head
    title
      | SampleApp
    = csrf_meta_tags
    = csp_meta_tag
    link[rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"]

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-light.readers class='#{controller_name} #{action_name}'
    .container
      p.notice
        = notice
      p.alert
        = alert
      = yield

app/views/readers/home/index.html.slim
.row
  - @posts.each do |post|
    .col-md-6.col-lg-4
      .card.post-card
        = image_tag post.header_image, class: 'header-image'
        .card-body.d-flex.flex-column
          h5.card-title
            = post.title
          p.card-text
            = truncate(post.description, length: 250)
          = link_to 'Read Post', blog_post_path(post), class: 'btn btn-primary mt-auto'

app/views/readers/posts/show.html.slim
.row
  .col-lg-10.offset-lg-1
    .card.post-card.mb-5
      = image_tag @post.header_image, class: 'header-image'
      .card-body
        .pl-5.pr-5.pt-4.pb-4
          h1.card-title.mb-5
            = @post.title
          - @post.elements.each do |element|
            - if element.image?
              .image-element.mb-4
                = image_tag(element&.image)
            - else
              .content-element.mb-4
                = raw  element.content